---
title: "STAT 5310 Assignment3 Q3-Q5 code"
author: "Hao Xu T00732492"
date: "2024-04-01"
---

# Question 3

```{r}
pdf("Ast3-Q3.pdf",height=4.4,width=7)
par(mar=c(5,5,3,3))
mu<-seq(55,75,length=1000)

mu0 <- 65
tau02 <- 1
sigma2 <- 9

yi <- c(46 ,68 ,34 ,86 ,75 ,56 ,77 ,73 ,53 ,64)
sy <- sum(yi)
ny<- length(yi)

post_mumean <- (tau02*sy + sigma2*mu0)/(ny*tau02+sigma2)
post_muvar <- (sigma2*tau02)/(ny*tau02+sigma2)

plot(mu,dnorm(mu,mean=post_mumean,sd=sqrt(post_muvar)),type="l",ylab=
     expression(paste("Posterior: ",italic("p("),mu,"|",
		      y[1],",...,",y[n],",",sigma^2,",", mu[0],",",tau[0]^2,")",sep="")), 
     xlab=expression(mu), lwd=2)
mtext(expression(paste("Normal(",mu[0],"=65,",tau[0]^2,"=1) prior,  ", 
		       italic(sum(y[i])),"=632,",sigma^2,"=9",sep="")), side=3,line=.1)
lines(mu,dnorm(mu,mean=mu0,sd=tau02),type="l",col="gray",lwd=2)
abline(v=qnorm( c(.025,.975), mean=post_mumean, sd=sqrt(post_muvar)), lty=2)
abline(v=qnorm( c(.025,.975), mean=mu0, sd=sqrt(tau02)),  lty=3)
dev.off()
```
# Question 4

```{r}
yA<-c(12, 9, 12, 14, 13, 13, 15, 8, 15, 6)
yB<-c(11, 11, 10, 9, 9, 8, 7, 10, 6, 8, 8, 9, 7)
syA <- sum(yA)
syB <- sum(yB)
alphaA <- 120
alphaB <- 12
betaA <- 10
betaB <- 1

meanthetaA <- (alphaA + syA)/(betaA+length(yA))
meanthetaB <- (alphaB + syB)/(betaB+length(yB))
cat("mean of theta_A")
meanthetaA
cat("mean of theta_B")
meanthetaB
varthetaA <- (alphaA + syA)/((betaA+length(yA))^2)
varthetaB <- (alphaB + syB)/((betaB+length(yB))^2)
cat("variance of theta_A")
varthetaA 
cat("variance of theta_B")
varthetaB 
cat("95% quantile based credible interval of theata_A")
qgamma(c(0.025,0.975),alphaA + syA, (betaA+length(yA)))
cat("95% quantile based credible interval of theata_B")
qgamma(c(0.025,0.975),alphaB + syB, (betaB+length(yB)))

n0 <- seq(1,500,by=1)
alphaB <- n0*12
betaB <- n0*1

meanthetaB <- (alphaB + syB)/(betaB+length(yB))
pdf("Ast3-Q4-partb.pdf")
plot(n0, meanthetaB, type="l", ylim=c(8.9,12),xlab=expression(n[0]), ylab=expression(theta[B]))
abline(h=meanthetaA, lty=2)
abline(v=274, lty=2)
dev.off()


```

# Question 5

```{r}
# Define the target density function f(x)
f <- function(x) exp(-x^4 - x^6 - x^8)

# Metropolis-Hastings algorithm
metropolis_hastings <- function(iterations, proposal_sd) {
  x <- numeric(iterations)
  x[1] <- 0  # Initial value
  accept=1
  for (i in 2:iterations) {
    # Generate proposal from normal distribution
    proposal <- rnorm(1, mean = x[i - 1], sd = proposal_sd)
    
    # Calculate acceptance ratio
    alpha <- min(f(proposal) / f(x[i - 1]),1)
    
    # Accept or reject proposal
    if (runif(1) < alpha) {
      accept <- accept+1
      x[i] <- proposal
    } else {
      x[i] <- x[i - 1]
    }
  }
  
  print("Accept rate")
  print(accept/iterations)
  return(x)
}

# Number of iterations
iterations <- 10000

# Proposal distributions
proposal_sd_a <- 1
proposal_sd_b <- sqrt(10)

# Run Metropolis-Hastings algorithm with proposal (a)
set.seed(123)
mh_output_a <- metropolis_hastings(iterations, proposal_sd_a)

# Run Metropolis-Hastings algorithm with proposal (b)
set.seed(123)
mh_output_b <- metropolis_hastings(iterations, proposal_sd_b)

pdf("Ast3-Q5-hist.pdf",height=4.4,width=7)
par(mfrow = c(1, 2))
hist(mh_output_a,breaks=10,freq=F)
hist(mh_output_b,breaks=10,freq=F)
dev.off()

# Plot traceplots
pdf("Ast3-Q5-traceplots.pdf")
par(mfrow = c(2, 1))
plot(mh_output_a, type = 'p', xlab= 'iteration', ylab = expression(x[i]), 
     main = 'Traceplot (Proposal a)')
plot(mh_output_b, type = 'p', xlab= 'iteration', ylab = expression(x[i]), 
     main = 'Traceplot (Proposal b)')
dev.off()

stationarity.plot<-function(x,...){
S<-length(x)
scan<-1:S
ng<-min(round(S/100),10)
group<-S*ceiling( ng*scan/S) /ng
boxplot(x~group,...)
}
pdf("Ast3-Q5-stationarity-plot.pdf")
par(mfrow = c(2, 1))
stationarity.plot(mh_output_a,xlab="iteration",ylab=expression(x), 
		  main = 'Stationarity Plot (Proposal a)')
stationarity.plot(mh_output_b,xlab="iteration",ylab=expression(x), 
		  main = 'Stationarity Plot (Proposal b)')
dev.off()

pdf("Ast3-Q5-acf-plot.pdf")
par(mfrow = c(2, 1))
acf(mh_output_a,ci.col="gray",xlab="lag", main = 'autocorrelation function (Proposal a)')
acf(mh_output_b,ci.col="gray",xlab="lag", main = 'autocorrelation function (Proposal b)')
dev.off()

library(coda)
cat("\nEffective size of proposal a:\n")
effectiveSize(mh_output_a)
cat("\nEffective size of proposal b:\n")
effectiveSize(mh_output_b)

# Calculate E(X) and Var(X) for proposal (a)
mean_a <- mean(mh_output_a)
var_a <- var(mh_output_a)
cat("Proposal (a):\n")
cat("E(X):", mean_a, "\n")
cat("Var(X):", var_a, "\n")

```




